import test from 'node:test';
import assert from 'node:assert/strict';
import worker, { catalog } from '../src/worker.js';
const env={SESSION_TTL_SECONDS:'86400',ADMIN_BOOTSTRAP_EMAIL:'admin@cloudpress.test'};
async function call(path,{method='GET',body,cookie}={}){return worker.fetch(new Request(`https://bridge.example.com${path}`,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{})},body:body&&JSON.stringify(body)}),env)}
async function login(email='user@example.com'){await call('/api/auth/signup',{method:'POST',body:{email,name:'User',address:'Seoul',password:'pw'}}); const res=await call('/api/auth/login',{method:'POST',body:{email,password:'pw'}}); return res.headers.get('set-cookie').split(';')[0]}
test('catalog matches required pricing and product split',()=>{assert.equal(catalog.wordpress.plans.lite,14);assert.equal(catalog.wordpress.plans.duplex,76);assert.equal(catalog.cloudpressdb.price,10);assert.equal(catalog.cp3.basePrice,10);assert.equal(catalog.cp3.extraPerGb,0.5);assert.ok(catalog.cloudpressdb.types['wordpress-nosql']);assert.ok(catalog.cloudpressdb.types['general-sql']);});
test('signup, login, order cart path, and instance provisioning work',async()=>{const cookie=await login('flow@example.com'); let res=await call('/api/orders',{method:'POST',cookie,body:{product:'wordpress',plan:'lite'}}); assert.equal(res.status,201); let data=await res.json(); assert.match(data.cartPath,/^\/wordpress\/cart\/bill_/); res=await call('/api/instances',{method:'POST',cookie,body:{type:'wordpress',name:'wp'}}); data=await res.json(); assert.equal(data.instance.database,'CloudPressDB wordpress-nosql'); assert.equal(data.instance.storage,'CP3 separate product');});
test('CloudPressDB KV/SQL and CP3 object APIs work for authenticated users',async()=>{const cookie=await login('data@example.com'); let res=await call('/api/cloudpressdb/kv',{method:'POST',cookie,body:{key:'hello',value:'world'}}); assert.equal(res.status,200); res=await call('/api/cloudpressdb/sql',{method:'POST',cookie,body:{sql:'create table posts (id,title)'}}); assert.equal((await res.json()).ok,true); res=await call('/api/cloudpressdb/sql',{method:'POST',cookie,body:{sql:'insert into posts (id,title) values (?,?)',params:['1','Post']}}); assert.equal((await res.json()).rows[0].title,'Post'); res=await call('/api/cp3/objects',{method:'POST',cookie,body:{name:'file.txt',data:'payload'}}); assert.equal(res.status,201); assert.equal((await res.json()).object.size,7);});
test('static route renders the app shell',async()=>{const res=await call('/products'); assert.equal(res.status,200); assert.match(await res.text(),/data-page="\/bridge\/products.html"/);});
